"""
campaign.py — CONFIRMATORY plane Tier-2 enumerator (Amendment-02 §B2-B4; Amendment-04 D4).

Certified real-box enumeration of each well-posed plane subset by branch-and-prune:
rigorous outward-rounded affine-arithmetic (aar.AAr) exclusion + AA-Krawczyk
interval-Newton certification, confined to the admissible domain (admissibility.py,
Amendment 04 D4). Per §B2(iv) the arithmetic is rigorous. Per §B3 a subset is
completeness-bearing iff the queue is exhausted within the frozen budget AND no
box is left unresolved (depth-capped); otherwise it is downgraded to Tier-1.

Box: B_plane, loaded from B.json (Amendment 03; generated by generate_B.py).
Frozen dependencies: aar.py, plane_chain.py, admissibility.py, sriyantra_plane.py
(v0.1.0 engine under test), B.json. No dependency on exploratory tooling.

FROZEN PARAMETERS are defined once below and must be hash-pinned (§B8) before any
confirmatory run. Gate M (gate_m.py) must pass on the frozen tree first (§B7).

Usage:  python3 campaign.py info            # params + population size
        python3 campaign.py <start> <end>   # census subsets [start:end], append CSV
        python3 campaign.py summary          # aggregate the results CSV
"""
import os, sys, csv, json, time, itertools
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE)); sys.path.insert(0, HERE)
import numpy as np
import sriyantra_plane as SP
from aar import AAr, DualR
from plane_chain import cons_full, Fvec
from admissibility import domain_excluded, classify_seam, RMAX
from scipy.optimize import fsolve

# ============================ FROZEN PARAMETERS (§B8) ============================
with open(os.path.join(HERE, "B.json")) as _f:                  # registered region (Amendment 03)
    _B = json.load(_f)["box"]
BOX        = [tuple(_B[k]) for k in ("b","c","d","e","g")]
R_CERT     = 3e-3            # AA-Krawczyk certification radius
MAX_DEPTH  = 200            # subdivision-depth cap (Amendment 04 D4); reaching it -> unresolved
MAX_BOXES  = 3_000_000       # safety budget (boxes) -> exceed = Tier-1 downgrade
TLIM       = 1800.0          # safety budget (seconds/subset) -> exceed = Tier-1 downgrade
BISECTION  = "widest-coordinate"   # documented split rule
DEDUP_TOL  = 2*R_CERT        # merge certified boxes closer than this
GATE2_TOL  = 1e-9            # engine round-trip residual accepted as a real figure
POLISH     = True            # Newton-polish certified roots to full precision
# RMAX (geometric coordinate bound) is frozen in admissibility.py (Amendment 04 D4).
# ===============================================================================

POOL=list(range(3,21)); DEGEN=(1,2,8,9,16)
def population():
    return [S for S in (tuple(sorted((1,2)+c)) for c in itertools.combinations(POOL,3)) if S!=DEGEN]

def excluded(box,S):
    AAr._n=[0]
    try: F=cons_full(*[AAr.var((lo+hi)/2,(hi-lo)/2) for (lo,hi) in box])
    except (ValueError,ZeroDivisionError): return False
    for k in S:
        lo,hi=F[k].iv()
        if not (lo<=0<=hi): return True
    return False

def hw(x): lo,hi=x.iv(); return (hi-lo)/2
def krawczyk(center,r,S):
    AAr._n=[0]
    try: Fd=cons_full(*[DualR.var(k,center[k],r) for k in range(5)])
    except (ValueError,ZeroDivisionError): return 'split'
    Jmid=np.array([[Fd[S[i]].grad[j].c for j in range(5)] for i in range(5)])
    Jrad=np.array([[hw(Fd[S[i]].grad[j]) for j in range(5)] for i in range(5)])
    if not np.all(np.isfinite(Jmid)): return 'split'
    try: Y=np.linalg.inv(Jmid)
    except np.linalg.LinAlgError: return 'split'
    Fm=Fvec(center,S); Mmid=np.eye(5)-Y@Jmid; Mrad=np.abs(Y)@Jrad
    Kc=-(Y@Fm); Khw=(np.abs(Mmid)+Mrad)@np.full(5,r)
    lo=np.array(center)+Kc-Khw; hi=np.array(center)+Kc+Khw
    Xlo=np.array(center)-r; Xhi=np.array(center)+r
    if np.all(hi<Xhi) and np.all(lo>Xlo): return 'unique'
    if np.any(hi<Xlo) or np.any(lo>Xhi): return 'empty'
    return 'split'

def polish(center,S):
    def resid(x): F=SP.constraints(*x); return [F[k] for k in S]
    try:
        x,info,ier,_=fsolve(resid,center,full_output=True)
        if ier==1: return list(map(float,x)), float(max(abs(v) for v in resid(x)))
    except Exception: pass
    return list(center), float('nan')

def enum_subset(S):
    t0=time.time(); stack=[(list(BOX),0)]; cert=[]; proc=0; maxq=1; maxd=0
    dom_excl=0; unresolved=[]
    while stack and proc<MAX_BOXES and time.time()-t0<TLIM:
        maxq=max(maxq,len(stack)); box,depth=stack.pop(); maxd=max(maxd,depth); proc+=1
        if domain_excluded(box): dom_excl+=1; continue          # Amendment 04 D4 (domain-first, as validated)
        if excluded(box,S): continue
        center=[(lo+hi)/2 for (lo,hi) in box]; rad=max((hi-lo)/2 for (lo,hi) in box)
        if rad<=R_CERT:
            v=krawczyk(center,rad,S)
            if v=='unique':
                if not any(max(abs(center[i]-q[i]) for i in range(5))<DEDUP_TOL for q in cert):
                    cert.append(center)
                continue
            if v=='empty': continue
        if depth>=MAX_DEPTH:                                     # depth cap -> unresolved (feeds §B3)
            unresolved.append(center); continue
        w=[hi-lo for (lo,hi) in box]; k=int(np.argmax(w)); lo,hi=box[k]; mid=(lo+hi)/2
        L=list(box); L[k]=(lo,mid); R=list(box); R[k]=(mid,hi)
        stack+=[(L,depth+1),(R,depth+1)]
    # §B3: completeness-bearing iff queue exhausted AND no unresolved box remains
    queue_clear=(len(stack)==0); complete=queue_clear and (len(unresolved)==0)
    # D5 diagnostic: localize any unresolved population
    seam={}
    for c in unresolved:
        k=classify_seam(c); seam[k]=seam.get(k,0)+1
    roots=[]
    for c in cert:
        xp,res=(polish(c,S) if POLISH else (c,float('nan')))
        roots.append({"coords":xp,"engine_residual":res,"gate2":bool(res<=GATE2_TOL)})
    if not complete:
        reason = "unresolved" if (queue_clear and unresolved) else "budget-exhausted"
    else:
        reason = ""
    return dict(subset=S,complete=complete,feasible=int(len(cert)>0),cert=len(cert),
                boxes=proc,peak_queue=maxq,max_depth=maxd,secs=round(time.time()-t0,1),
                dom_excl=dom_excl,unresolved=len(unresolved),seam=seam,downgrade=reason,roots=roots)

OUT=os.path.join(HERE,"campaign_results"); os.makedirs(OUT,exist_ok=True)
CSVP=os.path.join(OUT,"results.csv"); ROOTSP=os.path.join(OUT,"roots.jsonl")
COLS=["idx","subset","complete","feasible","cert","boxes","peak_queue","max_depth",
      "dom_excl","unresolved","downgrade","secs"]

def run_one(args):
    idx,S=args; r=enum_subset(S); r["idx"]=idx; return r

def run_range(start,end):
    pop=population(); end=min(end,len(pop)); tasks=[(i,pop[i]) for i in range(start,end)]
    newc=not os.path.exists(CSVP)
    fc=open(CSVP,"a",newline=""); w=csv.writer(fc)
    if newc: w.writerow(COLS)
    fr=open(ROOTSP,"a")
    nproc=os.cpu_count() or 1
    print(f"Campaign census subsets [{start}:{end}] of {len(pop)} on {nproc} core(s)")
    def handle(r):
        w.writerow([r["idx"],str(r["subset"]),r["complete"],r["feasible"],r["cert"],
                    r["boxes"],r["peak_queue"],r["max_depth"],r["dom_excl"],
                    r["unresolved"],r["downgrade"],r["secs"]]); fc.flush()
        fr.write(json.dumps({"idx":r["idx"],"subset":r["subset"],"roots":r["roots"],
                             "seam":r["seam"]})+"\n"); fr.flush()
        flag=f"  [TIER-1 DOWNGRADE: {r['downgrade']}]" if not r["complete"] else ""
        seamtxt=f" seam={r['seam']}" if r["seam"] else ""
        print(f"  idx={r['idx']:>3} {str(r['subset']):16s} cert={r['cert']} "
              f"boxes={r['boxes']:>8} q={r['peak_queue']:>4} d={r['max_depth']:>3} "
              f"domX={r['dom_excl']:>6} unres={r['unresolved']:>3} {r['secs']:>7}s "
              f"complete={r['complete']}{flag}{seamtxt}")
    if nproc>1:
        from multiprocessing import Pool
        with Pool(nproc) as p:
            for r in p.imap_unordered(run_one,tasks): handle(r)
    else:
        for t in tasks: handle(run_one(t))
    fc.close(); fr.close()

def summary():
    import statistics
    rows=list(csv.DictReader(open(CSVP)))
    n=len(rows); comp=[r for r in rows if r["complete"]=="True"]
    cens=[r for r in rows if r["complete"]!="True"]
    feas=[r for r in comp if r["feasible"]=="1"]; inf=[r for r in comp if r["feasible"]=="0"]
    boxes=sorted(int(r["boxes"]) for r in rows)
    print(f"Campaign — {n} of {len(population())} subsets processed\n")
    print(f"complete & feasible:   {len(feas)}")
    print(f"complete & infeasible: {len(inf)}")
    print(f"TIER-1 downgrades: {len(cens)}"
          + (f"  {[(r['subset'],r['downgrade']) for r in cens]}" if cens else ""))
    if boxes:
        print(f"\nboxes: min {boxes[0]}  median {int(statistics.median(boxes))}  "
              f"max {boxes[-1]}  total {sum(boxes)}")
    print(f"certified figures total: {sum(int(r['cert']) for r in rows)}")
    tot_unres=sum(int(r['unresolved']) for r in rows)
    print(f"unresolved boxes total: {tot_unres}")

if __name__=="__main__":
    a=sys.argv[1:]
    if not a or a[0]=="info":
        print(f"FROZEN: R_CERT={R_CERT} MAX_DEPTH={MAX_DEPTH} MAX_BOXES={MAX_BOXES} "
              f"TLIM={TLIM} BISECTION={BISECTION} RMAX={RMAX} GATE2_TOL={GATE2_TOL}")
        print(f"BOX (B_plane, from B.json)={[(round(a,6),round(b,6)) for a,b in BOX]}")
        print(f"population (well-posed plane subsets) = {len(population())}")
    elif a[0]=="summary": summary()
    else: run_range(int(a[0]), int(a[1]))
