# Tier-2 FAMILY campaign driver — coefficient-parameter homotopy
# Generated by lift_family.py.  DEV / pre-confirmatory.
#
# Usage:
#   julia -t 4,1 family_solve.jl                    # all 4 families, all 816 targets
#   julia -t 4,1 family_solve.jl --type=Q3          # one family (L3|L2Q1|L1Q2|Q3)
#   julia -t 4,1 family_solve.jl --type=Q3 --max-targets=3   # smoke test
#
# Output: family_results.jsonl (one JSON record per subset) + stdout summary.
# Requires: julia -e 'using Pkg; Pkg.add(["HomotopyContinuation","JSON"])'
using HomotopyContinuation, LinearAlgebra, Random
import JSON

@var b c d e g x1 x2 x3 x4 x5 x6 x7 x10 x11 x13 x16 x17 x18 x19 U7 U8 U9 U12 U20 U21 w
vars = [b, c, d, e, g, x1, x2, x3, x4, x5, x6, x7, x10, x11, x13, x16, x17, x18, x19, U7, U8, U9, U12, U20, U21, w]

# ---- fixed equations: 28 chain + F1 + F2 ----
fixed_eqs = [
    c^2 + x1^2 - 1,   # x1
    d^2 + x2^2 - 1,   # x2
    c*x2 + d*x3 - x2 + x3,   # x3
    c*x4 + d*x1 - x1 + x4,   # x4
    -b*x4 + b*x5 + c*x5 + d*x5,   # x5
    c*x6 + d*x6 - e*x3 + e*x6,   # x6
    U7*c*x6 + U7*d*x5 + U7*d*x6 + U7*g*x5 - c*d*x6 - c*g*x6 - d^2*x6 - d*g*x6,   # U7
    -U7*x5 + c*x7 + d*x7,   # x7
    U8*c*x6 + U8*d*x1 + U8*g*x1 + U8*x6 - c*g*x6 - c*x6 - g*x6 - x6,   # U8
    d*x16 - d*x6 - e*x6 + g*x16 - g*x6,   # x16
    c*x11 + d*x11 - d*x5 - g*x5,   # x11
    b*x10 - b*x4 + c*x10 - c*x4 + d*x10 + g*x4,   # x10
    U9*c*x2 + U9*d*x2 + U9*d*x5 + U9*x5 - d^2*x5 - 2*d*x5 - x5,   # U9
    -U12*U8*x6 + U12*d*x10 + U12*g*x10 + U12*g*x6 + U12*x6 + U8*d*x10 + U8*g*x10 - d*g*x10 - d*x10 - g^2*x10 - g*x10,   # U12
    U12*x3 + c*x13 + d*x13 - d*x3 + e*x13 - e*x3 - g*x3,   # x13
    -U7^2 + 2*U7*d + 2*U7*g - d^2 - 2*d*g - g^2 + w^2 - x7^2,   # w
    -b*x5 + c*x17 - c*x5 + d*x17 - d*x5,   # x17
    U8*x4 + b*x18 - b*x4 + c*x18 - c*x4 + d*x18 - x4,   # x18
    U9*x3 + c*x19 + d*x19 - d*x3 + e*x19 - e*x3 - x3,   # x19
    U12*U20*x10 - U20*U8*x13 - U20*U9*x10 - U20*g*x10 + U20*g*x13 + U20*x10 + U20*x13 - U8^2*x13 - U8*U9*x13 + U8*g*x13 + 3*U8*x13 + U9*g*x13 + U9*x13 - 2*g*x13 - 2*x13,   # U20
    -U21*U8*x19 - U21*U9*x18 + U21*b*x19 + U21*c*x19 + U21*d*x18 + U21*e*x18 + U21*x18 + U21*x19 + U9*b*x18 + U9*c*x18 + U9*d*x18 + U9*e*x18 - b*d*x18 - b*e*x18 - b*x18 - c*d*x18 - c*e*x18 - c*x18 - d^2*x18 - 2*d*e*x18 - d*x18 - e^2*x18 - e*x18,   # U21
    U12*x11 - U9*x11 + U9*x13 - g*x11 + g*x13 + x11 - x13,   # F1
    U7^2 - 2*U7*d - U7*g + d^2 + d*g - w*x7 + x7^2,   # F2
]

# ---- constraint pool (engine equivalence validated in lift_family.py) ----
poolpoly = Dict{Int,Expression}(
    5 => x10 - x13,   # F5, factor 1
    7 => x18 - x19,   # F7, factor 1
    10 => U8 + b + c - 2*g - 1,   # F10, factor 1
    11 => 2*U12 - U9 - d - e - 2*g + 1,   # F11, factor 1
    12 => x16 - x17,   # F12, factor 1
    13 => U12 - U20 + 2*U7 - U8 - 2*d - g + 1,   # F13, factor 2
    14 => -2*U12 - U21 + 2*d + e + 2*g,   # F14, factor 2
    15 => -U21 - c + d + e + 2*g,   # F15, factor 2
    20 => c - d,   # F20, factor 1
    3 => -U8^2 + 2*U8*g + 2*U8 - g^2 - 2*g + 3*x10^2 - 1,   # F3, factor 2
    4 => -U12^2 + 2*U12*U9 + 2*U12*g - 2*U12 - U9^2 - 2*U9*g + 2*U9 - g^2 + 2*g + 3*x13^2 - 1,   # F4, factor 2
    6 => -U7^2 + 2*U7*d + 2*U7*g - d^2 - 2*d*g - g^2 + 3*x7^2,   # F6, factor 2
    8 => d^2 + 2*d*e + e^2 + x16^2 - 1,   # F8, factor -(r16+1)
    9 => b^2 + 2*b*c + c^2 + x17^2 - 1,   # F9, factor -(r17+1)
    16 => -b^2 - 2*b*c - c^2 + d^2 + 2*d*e + e^2 + x16^2 - x17^2,   # F16, factor r16+r17
    17 => U8^2 - 2*U8 - U9^2 + 2*U9 + x18^2 - x19^2,   # F17, factor r18+r19
    18 => -U8^2 + 2*U8 + d^2 + 2*d*e + e^2 + x16^2 - x18^2 - 1,   # F18, factor r16+r18
    19 => -U9^2 + 2*U9 + b^2 + 2*b*c + c^2 + x17^2 - x19^2 - 1,   # F19, factor r17+r19
)
LIN  = [5, 7, 10, 11, 12, 13, 14, 15, 20]
QUAD = [3, 4, 6, 8, 9, 16, 17, 18, 19]

# ---- verified start point on the chain+F1+F2 variety (plane optimum) ----
seed = ComplexF64[0.4823912175798971, 0.261039, 0.287454, 0.467384, 0.10846327131099652, 0.9653282552992013, 0.9577944444837838, 0.549746041792702, 0.5454556020871874, 0.2552401012058575, 0.25292678542504676, 0.1065934776833941, 0.3359701041845884, 0.18423929639679212, 0.31501967854631285, 0.5515091945421321, 0.47971987249903675, 0.6556719400160884, 0.6815364071725707, 0.2290618757741511, 0.5042425508180899, 0.495425274714161, 0.2811756684798875, 0.45563379528007636, 0.7407068420568873, 0.19799720327418105]

# ---- admissibility filter (mirrors lift_poc.py Test 5) ----
const iB,iC,iD,iE,iG = 1,2,3,4,5
const iX1,iX2,iW = 6,7,26
const iU7,iU9,iU12 = 20,22,23
function admissible(s::Vector{Float64}; pos_tol=1e-9, den_tol=1e-7, lo=1e-6)
    s[iX1]>pos_tol && s[iX2]>pos_tol && s[iW]>pos_tol || return false
    all(s[i]>lo for i in (iB,iC,iD,iE,iG)) || return false
    s[iC]<1 && s[iD]<1 || return false
    # Q-clearing denominators eliminated; only the genuine ones remain
    dens = (s[iD]+s[iG]-s[iU7], 1-s[iU9]-s[iG]+s[iU12])
    all(abs(q)>den_tol for q in dens)
end

# ---- family construction ----
# type => (slot pools);  a subset's slots are filled lin-first, sorted
FAMS = Dict(
    "L3"   => [LIN, LIN, LIN],
    "L2Q1" => [LIN, LIN, QUAD],
    "L1Q2" => [LIN, QUAD, QUAD],
    "Q3"   => [QUAD, QUAD, QUAD],
)
famname(nl) = ("Q3","L1Q2","L2Q1","L3")[nl+1]

function build_family(fam::String)
    pools = FAMS[fam]
    params = Variable[]; slots = Expression[]
    for (j, P) in enumerate(pools)
        aj = [Variable(Symbol("a$(j)_$(k)")) for k in 1:length(P)]
        append!(params, aj)
        push!(slots, sum(aj[i]*poolpoly[P[i]] for i in 1:length(P)))
    end
    F = System([fixed_eqs; slots]; variables=vars, parameters=params)
    F, pools
end

# generic parameters vanishing at `seed`: per slot, random complex coeffs
# projected onto the hyperplane  sum_i a_i * P_i(seed) = 0
function generic_params_at_seed(pools; rng=Random.default_rng())
    p0 = ComplexF64[]
    for P in pools
        u = [ComplexF64(evaluate(poolpoly[k], vars => seed)) for k in P]
        a = randn(rng, ComplexF64, length(P))
        a .-= (transpose(u)*a / (transpose(u)*u)) .* u   # unconjugated dot
        @assert abs(sum(a .* u)) < 1e-10
        append!(p0, a)
    end
    p0
end

# 0/1 parameter vector for a concrete subset (lin-first, sorted order)
function target_params(T::Vector{Int}, pools)
    Tl = sort([k for k in T if k in LIN]); Tq = sort([k for k in T if k in QUAD])
    chosen = vcat(Tl, Tq)
    @assert length(chosen) == length(pools)
    pt = ComplexF64[]
    for (j, P) in enumerate(pools)
        v = zeros(ComplexF64, length(P)); v[findfirst(==(chosen[j]), P)] = 1
        append!(pt, v)
    end
    pt
end

# ---- target census ----
alltriples = [sort(collect(T)) for T in
    Iterators.filter(t -> length(t)==3,
        [ [i,j,k] for i in 3:20 for j in i+1:20 for k in j+1:20 ])]
DEGEN = Set([8,9,16])

# ---- CLI ----
want_type = nothing; max_targets = typemax(Int)
for a in ARGS
    startswith(a, "--type=")        && (global want_type   = split(a,"=")[2])
    startswith(a, "--max-targets=") && (global max_targets = parse(Int, split(a,"=")[2]))
end

results_io = open("family_results.jsonl", "a")

for fam in ["L3","L2Q1","L1Q2","Q3"]
    (want_type === nothing || want_type == fam) || continue
    println("\n", "="^70); println("FAMILY ", fam); println("="^70)
    F, pools = build_family(fam)

    # --- generic solve: ab-initio POLYHEDRAL (seed-free, complete by BKK) ---
    # Once the (Q+1)/x11a artifact loci are removed the generic member is
    # cheap to solve directly. Monodromy from a single seed under-saturated
    # (returned N*=1); polyhedral is complete by construction and measures N*.
    p0 = generic_params_at_seed(pools; rng=MersenneTwister(20260612))
    t_gen = @elapsed res0 = solve(F; target_parameters = p0)
    S = solutions(res0)
    Nstar = length(S)
    npaths = length(path_results(res0))
    println("N* ($fam) = $Nstar generic solutions  ",
            "(polyhedral: $npaths paths, ", round(t_gen, digits=1), "s)")

    # --- monodromy cross-check: seed with the polyhedral set, raised budget;
    #     a BKK-complete set must NOT grow under monodromy ---
    agree = true
    if Nstar > 0
        try
            mres = monodromy_solve(F, S, p0;
                max_loops_no_progress = 50, unique_points_rtol = 1e-10)
            agree = (length(solutions(mres)) <= Nstar)
            println("monodromy cross-check: ", length(solutions(mres)),
                    " (<= N*: ", agree, ")")
        catch err
            println("monodromy cross-check skipped: ", err)
        end
    end

    # --- trace-test completeness certificate (hardened against empty set) ---
    cert_ok = false
    if Nstar == 0
        println("trace-test completeness: SKIPPED (empty generic set)")
    else
        try
            v = verify_solution_completeness(F, S, p0; trace_tol = 1e-10)
            cert_ok = (v === true)
            println("trace-test completeness: ", v)
        catch err
            println("trace-test completeness: ERROR ", err)
        end
    end
    JSON.print(results_io, Dict("family_summary" => fam,
        "Nstar" => Nstar, "trace_test_passed" => cert_ok,
        "generic_paths" => npaths,
        "monodromy_crosscheck_agree" => agree,
        "generic_solve_seconds" => round(t_gen, digits=1)))
    write(results_io, '\n'); flush(results_io)

    # --- sweep all targets of this family type ---
    targets = [T for T in alltriples if famname(count(in(LIN), T)) == fam]
    ndone = 0
    for T in targets
        ndone >= max_targets && break; ndone += 1
        pt = target_params(T, pools)
        t_solve = @elapsed res = solve(F, S; start_parameters=p0,
            target_parameters=pt, show_progress=false)
        pr = path_results(res)
        nfail = count(r -> !is_success(r) && !is_at_infinity(r), pr)
        # non-singular only: singular endpoints at non-generic 0/1 targets
        # are expected lifting artifacts, not isolated solutions.
        rs = real_solutions(res; only_nonsingular = true)
        adm = [s for s in rs if admissible(s)]
        ncert = -1
        try
            ncert = ndistinct_certified(certify(F,
                solutions(res; only_nonsingular = true);
                target_parameters = pt))
        catch; end
        rec = Dict(
            "subset" => vcat([1,2], T), "family" => fam,
            "expected_degenerate" => issubset(DEGEN, Set(T)),
            "Nstar_paths" => Nstar, "path_failures" => nfail,
            "n_solutions" => nsolutions(res), "n_real" => length(rs),
            "n_admissible" => length(adm),
            "n_certified_distinct" => ncert,
            "admissible_bcdeg" => [round.(s[[iB,iC,iD,iE,iG]], digits=10)
                                    for s in adm],
            "completeness_bearing" => (cert_ok && nfail == 0),
            "runtime_s" => round(t_solve, digits=2),
        )
        JSON.print(results_io, rec); write(results_io, '\n'); flush(results_io)
        tag = rec["expected_degenerate"] ? "  [GATE-1: expect non-isolated]" : ""
        println("{1,2}+", T, "  real=", length(rs), " adm=", length(adm),
                " fail=", nfail, " ", round(t_solve,digits=1), "s", tag)
    end
end
close(results_io)
println("\nDone. Records appended to family_results.jsonl")
