#!/usr/bin/env python3
"""Generate assets/constraints.js FROM the frozen constraint registry (chain_sphere.py).
The engine expression text is extracted verbatim from constraints_sph (source of truth),
not hand-written; descriptions and equation numbers follow Rao (1998) Section 3."""
import re, json, sys, os
_here = os.path.dirname(os.path.abspath(__file__))
_root = _here
while _root != os.path.dirname(_root):
    if os.path.exists(os.path.join(_root, "sriyantra.py")):
        break
    _root = os.path.dirname(_root)
for _p in (_here, _root, os.path.join(_root, "enumeration")):
    if os.path.isdir(_p) and _p not in sys.path:
        sys.path.insert(0, _p)

SRC = os.path.join(os.path.dirname(os.path.abspath(__file__)), "chain_sphere.py")
DESC = {  # Rao (1998) §3, spherical form (verified against the frozen engines in this project)
 1:("concurrency at point 11","Concurrency at point 11 — the two constructed locations of point 11 coincide (the essential closure condition of the figure).","3.1"),
 2:("concentricity","Concentricity — the inscribed circle of the innermost triangle shares the centre of the bounding circle.","3.2"),
 3:("P8 triangle equilateral","The root triangle with vertex at P8 is (spherically) equilateral.","3.3"),
 4:("P2 triangle equilateral","The root triangle with vertex at P2 is (spherically) equilateral.","3.4"),
 5:("equal base arcs 13 / 10","Base arcs P6·13 and P4·10 are equal.","3.5"),
 6:("P4 triangle equilateral","The innermost secondary triangle with vertex at P4 is (spherically) equilateral.","3.6"),
 7:("equal base arcs 18 / 19","Base arcs P8·18 and P2·19 are equal.","3.7"),
 8:("point 16 on bounding circle","Point 16 lies on the bounding circle of the cap.","3.8"),
 9:("point 17 on bounding circle","Point 17 lies on the bounding circle of the cap.","3.9"),
 10:("equal intercepts P1P4 / P4P8","Axial intercepts P1·P4 and P4·P8 are equal.","3.10"),
 11:("equal intercepts P9P6 / P6P2","Axial intercepts P9·P6 and P6·P2 are equal.","3.11"),
 12:("equal base arcs 16 / 17","Base arcs P9·16 and P1·17 are equal.","3.12"),
 13:("inner concurrency (P5)","Inner concurrency — P5 is the midpoint of arc P6·P20.","3.13"),
 14:("inner concurrency (P6)","Inner concurrency — P6 is the midpoint of arc P7·P21.","3.14"),
 15:("inner concurrency (P4)","Inner concurrency — P4 is the midpoint of arc P3·P21.","3.15"),
 16:("points 16, 17 equidistant","Points 16 and 17 are equidistant from the centre.","3.16"),
 17:("points 18, 19 equidistant","Points 18 and 19 are equidistant from the centre.","3.17"),
 18:("points 16, 18 equidistant","Points 16 and 18 are equidistant from the centre.","3.18"),
 19:("points 17, 19 equidistant","Points 17 and 19 are equidistant from the centre.","3.19"),
 20:("symmetry (c = d)","The outermost root triangles are identical — the up–down symmetry constraint c = d.","3.20"),
}

src = open(SRC).read()
body = src.split("def constraints_sph", 1)[1]
formulas = {}
for m in re.finditer(r"if\s+(\d+)\s+in W:\s*F\[\1\]\s*=\s*(.+)", body):
    n = int(m.group(1)); expr = m.group(2).strip()
    expr = re.sub(r"s\['(\w+)'\]", r"\1", expr)          # s['x11'] -> x11
    expr = expr.replace("iso(", "iso(")                    # keep engine helper name
    formulas[n] = expr
assert set(formulas) == set(range(1, 21)), f"expected F1..F20, got {sorted(formulas)}"

out = {n: {"f": formulas[n], "short": DESC[n][0], "desc": DESC[n][1], "eq": DESC[n][2]} for n in range(1, 21)}
js = ("/* GENERATED by gen_constraints_js.py FROM the frozen constraint registry chain_sphere.py\n"
      " * (engine expression text verbatim, s[...] dereferenced; iso(V,x) = cos(V) - cos(2x)/cos(x)).\n"
      " * Descriptions and equation numbers: Rao (1998) Section 3. Do not edit by hand. */\n"
      "export const CONSTRAINTS = " + json.dumps(out, indent=1, ensure_ascii=False) + ";\n"
      "export const FIXED_BASE = [1, 2]; // every census subset contains F1, F2\n"
      "export const ISO_NOTE = 'iso(V, x) := cos(V) \\u2212 cos(2x)/cos(x) (spherical equilateral condition)';\n")
open("constraints.js", "w").write(js)
print("wrote constraints.js with", len(out), "constraints")
for n in (1, 3, 13, 20): print(f"  F{n}: {out[n]['f']}")
