# Tier-2 homotopy solve — subset {1,2,3,4,8}  (DEV / pre-confirmatory)
# Generated by lift_poc.py. Run: julia thisfile.jl
using HomotopyContinuation
@var b c d e g x1 x2 x3 x4 x5 x6 x7 x10 x11 x13 x16 U7 U8 U9 U12 Q7 Q8 Q9 Q12 x11a w
eqs = [
    c^2 + x1^2 - 1,   # x1
    d^2 + x2^2 - 1,   # x2
    c*x2 + d*x3 - x2 + x3,   # x3
    c*x4 + d*x1 - x1 + x4,   # x4
    -b*x4 + b*x5 + c*x5 + d*x5,   # x5
    c*x6 + d*x6 - e*x3 + e*x6,   # x6
    Q7*c*x6 + Q7*d*x6 - d*x5 - g*x5,   # Q7
    Q7*U7 + U7 - d - g,   # U7
    -U7*x5 + c*x7 + d*x7,   # x7
    Q8*c*x6 + Q8*x6 - d*x1 - g*x1,   # Q8
    Q8*U8 + U8 - g - 1,   # U8
    d*x16 - d*x6 - e*x6 + g*x16 - g*x6,   # x16
    c*x11 + d*x11 - d*x5 - g*x5,   # x11
    b*x10 - b*x4 + c*x10 - c*x4 + d*x10 + g*x4,   # x10
    Q9*d*x5 + Q9*x5 - c*x2 - d*x2,   # Q9
    Q9*U9 + U9 - d - 1,   # U9
    Q12*d*x10 + Q12*g*x10 + U8*x6 - g*x6 - x6,   # Q12
    Q12*U12 + U12 + U8 - g - 1,   # U12
    U12*x3 + c*x13 + d*x13 - d*x3 + e*x13 - e*x3 - g*x3,   # x13
    U12*x11a - U9*x11a + U9*x13 - g*x11a + g*x13 + x11a - x13,   # x11a
    -U7^2 + 2*U7*d + 2*U7*g - d^2 - 2*d*g - g^2 + w^2 - x7^2,   # w
    x11 - x11a,   # F1
    U7^2 - 2*U7*d - U7*g + d^2 + d*g - w*x7 + x7^2,   # F2
    -U8^2 + 2*U8*g + 2*U8 - g^2 - 2*g + 3*x10^2 - 1,   # F3
    -U12^2 + 2*U12*U9 + 2*U12*g - 2*U12 - U9^2 - 2*U9*g + 2*U9 - g^2 + 2*g + 3*x13^2 - 1,   # F4
    d^2 + 2*d*e + e^2 + x16^2 - 1,   # F8
]
vars = [b, c, d, e, g, x1, x2, x3, x4, x5, x6, x7, x10, x11, x13, x16, U7, U8, U9, U12, Q7, Q8, Q9, Q12, x11a, w]
F = System(eqs; variables = vars)
result = solve(F)

# certify ONLY non-singular solutions: interval certification
# diverges on singular endpoints (rank-deficient Jacobian).
ns   = solutions(result; only_nonsingular = true)
cert = certify(F, ns)

# admissible-branch filter (sign + range) over non-singular reals
adm = filter(real_solutions(result; only_nonsingular = true)) do s
    s[1]>1e-6 && s[2]>1e-6 && s[3]>1e-6 && s[4]>1e-6 && s[5]>1e-6 &&
    s[6]>1e-9 && s[7]>1e-9 && s[26]>1e-9 && s[2]<1 && s[3]<1
end
for s in adm; println("admissible: ", round.(s[1:5], digits=8)); end

println("paths tracked: ", length(path_results(result)))
println("non-singular solutions: ", length(ns))
println("certified distinct (non-singular): ", ndistinct_certified(cert))
println("admissible real (non-singular): ", length(adm))
